-- ==============================================================
-- Magnitude Analysis
-- ==============================================================
-- This script analyzes the distribution and scale of key business entities.
-- It examines how customers, products, and revenue are distributed across
-- different dimensions such as country, gender, and product categories.
-- Additionally, it evaluates average costs, total revenue by category,
-- customer-level revenue contribution, and sales distribution across countries.
-- This helps in understanding business performance and identifying key segments.
-- ==============================================================

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_id) AS total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT	
	gender,
	COUNT(*) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
	categroy,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY categroy
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT 
	categroy,
	AVG(product_cost) AS avg_cost
FROM gold.dim_products
GROUP BY categroy
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
	p.categroy,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.categroy
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue_per_customer
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key, 
	c.first_name, 
	c.last_name
ORDER BY total_revenue_per_customer DESC;

-- What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(f.quantity) AS total_items_per_country
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_per_country DESC;
